version: '1'
services:
  - type: static
    name: ilveliero-1
    buildCommand: pnpm install && cd artifacts/il-veliero && pnpm run build
    publishPath: artifacts/il-veliero/dist
    envVars:
      - key: PNPM_VERSION
        value: 9.1.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
